// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnU6_IY9rXuGIBzxMCdf0SXs7J65UZ8Fg',
    appId: '1:113153603365:web:ef85d4bc6ede4c0e208ccc',
    messagingSenderId: '113153603365',
    projectId: 'cinq-4d02f',
    authDomain: 'cinq-4d02f.firebaseapp.com',
    storageBucket: 'cinq-4d02f.appspot.com',
    measurementId: 'G-PE2B7Q8DKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNOZdcvBdvIehlw-h3UpoHmj9_lBfvOck',
    appId: '1:113153603365:android:1839123943ce8042208ccc',
    messagingSenderId: '113153603365',
    projectId: 'cinq-4d02f',
    storageBucket: 'cinq-4d02f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7xvuDrLC3UritjZUcLmLC8zDrvD8KJH4',
    appId: '1:113153603365:ios:d1defe53f5d57dc7208ccc',
    messagingSenderId: '113153603365',
    projectId: 'cinq-4d02f',
    storageBucket: 'cinq-4d02f.appspot.com',
    iosBundleId: 'com.example.appstage',
  );

}